# Generated by Django 5.2.8 on 2025-11-24 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MARKET_OPEN', 'Market Opening'), ('EARNINGS', 'Earnings Report'), ('POLICY', 'Government Policy'), ('GLOBAL', 'Global Impact'), ('SECTOR', 'Sector News'), ('IPO', 'IPO/Listings'), ('MERGER', 'Mergers & Acquisitions'), ('COMMODITY', 'Commodity News'), ('CURRENCY', 'Currency/Forex'), ('REGULATORY', 'Regulatory Changes'), ('OTHER', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#007bff', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('news_collection_started', models.DateTimeField(blank=True, null=True)),
                ('news_collection_completed', models.DateTimeField(blank=True, null=True)),
                ('analysis_completed', models.DateTimeField(blank=True, null=True)),
                ('recommendations_generated', models.DateTimeField(blank=True, null=True)),
                ('total_news_collected', models.PositiveIntegerField(default=0)),
                ('total_recommendations', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('rss_feed', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('is_nifty50', models.BooleanField(default=False)),
                ('is_sensex', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('PENDING', 'Pending Analysis')], default='PENDING', max_length=10)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('impact_level', models.CharField(choices=[('HIGH', 'High Impact'), ('MEDIUM', 'Medium Impact'), ('LOW', 'Low Impact'), ('PENDING', 'Pending Analysis')], default='PENDING', max_length=10)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('is_pre_market', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newssource')),
                ('mentioned_stocks', models.ManyToManyField(blank=True, to='news.stock')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('WATCH', 'Watch')], max_length=10)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_level', models.FloatField()),
                ('reasoning', models.TextField()),
                ('key_factors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('related_articles', models.ManyToManyField(blank=True, to='news.newsarticle')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', 'created_at'], name='news_recomm_stock_i_27e1f0_idx'), models.Index(fields=['recommendation'], name='news_recomm_recomme_fef055_idx'), models.Index(fields=['is_active', 'valid_until'], name='news_recomm_is_acti_85e8b3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['published_at'], name='news_newsar_publish_df29a9_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['sentiment'], name='news_newsar_sentime_3faad7_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['is_pre_market'], name='news_newsar_is_pre__d2ffff_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', 'published_at'], name='news_newsar_source__4b965e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userwatchlist',
            unique_together={('user', 'stock')},
        ),
    ]
