# Generated by Django 5.2.8 on 2025-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_stock_current_price_stock_price_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_recommendation',
            field=models.BooleanField(default=False),
        ),
    ]
