# Generated by Django 5.2.8 on 2025-11-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_is_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='ai_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='article_emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='impact_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='key_points',
            field=models.TextField(blank=True),
        ),
    ]
