# Generated by Django 5.2.8 on 2025-11-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticle_ai_summary_newsarticle_article_emoji_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'default', 'production')", max_length=100, unique=True)),
                ('gemini_model', models.CharField(default='gemini-1.5-flash', help_text='Gemini model name', max_length=100)),
                ('openai_model', models.CharField(default='gpt-3.5-turbo', help_text='OpenAI model name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
