# Generated by Django 5.2.8 on 2025-11-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_aiconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='gemini_model',
            field=models.CharField(default='gemini-2.5-flash', help_text='Gemini model name', max_length=100),
        ),
    ]
