# Generated by Django 5.2.8 on 2025-11-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0006_alter_aiconfig_gemini_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Portfolio', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('deal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.BigIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deal_date', models.DateField()),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_deals', to='news.stock')),
            ],
            options={
                'ordering': ['-deal_date'],
                'indexes': [models.Index(fields=['stock', '-deal_date'], name='portfolio_b_stock_i_cc84c3_idx'), models.Index(fields=['-deal_date'], name='portfolio_b_deal_da_dbb493_idx')],
            },
        ),
        migrations.CreateModel(
            name='BulkDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('deal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.BigIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deal_date', models.DateField()),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_deals', to='news.stock')),
            ],
            options={
                'ordering': ['-deal_date'],
                'indexes': [models.Index(fields=['stock', '-deal_date'], name='portfolio_b_stock_i_ba7b60_idx'), models.Index(fields=['-deal_date'], name='portfolio_b_deal_da_2266b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DIVIDEND', 'Dividend'), ('BONUS', 'Bonus Issue'), ('SPLIT', 'Stock Split'), ('RIGHTS', 'Rights Issue'), ('BUYBACK', 'Buyback'), ('MERGER', 'Merger/Amalgamation'), ('DELISTING', 'Delisting'), ('AGM', 'Annual General Meeting'), ('EGM', 'Extraordinary General Meeting')], max_length=20)),
                ('description', models.TextField()),
                ('ex_date', models.DateField(blank=True, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('announcement_date', models.DateField()),
                ('dividend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_ratio', models.CharField(blank=True, max_length=20)),
                ('split_ratio', models.CharField(blank=True, max_length=20)),
                ('rights_ratio', models.CharField(blank=True, max_length=20)),
                ('rights_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to='news.stock')),
            ],
            options={
                'ordering': ['-ex_date', '-announcement_date'],
                'indexes': [models.Index(fields=['stock', '-ex_date'], name='portfolio_c_stock_i_ead81f_idx'), models.Index(fields=['-ex_date'], name='portfolio_c_ex_date_bbaf5e_idx'), models.Index(fields=['action_type'], name='portfolio_c_action__32cd08_idx')],
            },
        ),
        migrations.CreateModel(
            name='InsiderTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insider_name', models.CharField(max_length=200)),
                ('insider_designation', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('PLEDGE', 'Pledge'), ('REVOKE', 'Revoke Pledge')], max_length=20)),
                ('quantity', models.BigIntegerField()),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_date', models.DateField()),
                ('intimation_date', models.DateField()),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insider_trades', to='news.stock')),
            ],
            options={
                'ordering': ['-transaction_date', '-intimation_date'],
                'indexes': [models.Index(fields=['stock', '-transaction_date'], name='portfolio_i_stock_i_8379b0_idx'), models.Index(fields=['-transaction_date'], name='portfolio_i_transac_eb6627_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.stock')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('portfolio', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='PromoterHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_end_date', models.DateField()),
                ('promoter_holding', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promoter_pledged', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('public_holding', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fii_holding', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dii_holding', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_shareholders', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoter_holdings', to='news.stock')),
            ],
            options={
                'ordering': ['-quarter_end_date'],
                'indexes': [models.Index(fields=['stock', '-quarter_end_date'], name='portfolio_p_stock_i_a64b9c_idx'), models.Index(fields=['-quarter_end_date'], name='portfolio_p_quarter_41eaf1_idx')],
                'unique_together': {('stock', 'quarter_end_date')},
            },
        ),
        migrations.CreateModel(
            name='ShareholdingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_end_date', models.DateField()),
                ('indian_promoters', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('foreign_promoters', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retail_investors', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('others', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mutual_funds', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('banks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fii', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dii', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholding_patterns', to='news.stock')),
            ],
            options={
                'ordering': ['-quarter_end_date'],
                'unique_together': {('stock', 'quarter_end_date')},
            },
        ),
    ]
